# Generated by Django 5.1.4 on 2024-12-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0003_delete_bilanradiologiqueimages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='demandebilan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='demanderadio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dpi',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicament',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ordonnancemedicament',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tuser',
            options={'managed': True},
        ),
    ]
