# Generated by Django 5.1.4 on 2024-12-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0005_alter_demandecertaficat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandecertaficat',
            options={'managed': True},
        ),
        
    ]
