# Generated by Django 5.1.4 on 2024-12-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billanbiologique',
            fields=[
                ('billanbiologiqueid', models.AutoField(db_column='billanBiologiqueId', primary_key=True, serialize=False)),
                ('typebilan', models.CharField(db_column='typeBilan', max_length=12)),
                ('graphimage', models.TextField(blank=True, db_column='graphImage', null=True)),
            ],
            options={
                'db_table': 'billanbiologique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billanradiologique',
            fields=[
                ('billanradiologiqueid', models.AutoField(db_column='billanRadiologiqueId', primary_key=True, serialize=False)),
                ('radiotype', models.CharField(db_column='RadioType', max_length=12)),
                ('compterendu', models.CharField(db_column='compteRendu', max_length=500)),
            ],
            options={
                'db_table': 'billanradiologique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billanradiologiqueimages',
            fields=[
                ('imageid', models.AutoField(db_column='imageId', primary_key=True, serialize=False)),
                ('imagedata', models.TextField(db_column='imageData')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'billanradiologiqueimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(db_column='patientId', max_length=100, primary_key=True, serialize=False)),
                ('nompatient', models.CharField(db_column='nomPatient', max_length=100)),
                ('prenompatient', models.CharField(db_column='prenomPatient', max_length=100)),
                ('adressepatient', models.CharField(db_column='adressePatient', max_length=100)),
                ('telephonepatient', models.CharField(db_column='telephonePatient', max_length=15)),
                ('mutuelle', models.IntegerField(blank=True, null=True)),
                ('etatpatient', models.IntegerField(db_column='etatPatient')),
                ('datedenaissancepatient', models.DateField(blank=True, db_column='dateDeNaissancePatient', null=True)),
                ('personneacontacter', models.CharField(blank=True, db_column='personneAContacter', max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('demandeid', models.AutoField(db_column='demandeId', primary_key=True, serialize=False)),
                ('etatdemande', models.IntegerField(db_column='etatDemande')),
                ('typedemande', models.CharField(db_column='typeDemande', max_length=17)),
                ('contenudemande', models.CharField(db_column='contenuDemande', max_length=100)),
                ('datedenvoi', models.DateField(blank=True, db_column='dateDenvoi', null=True)),
            ],
            options={
                'db_table': 'demande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('hopitalid', models.AutoField(db_column='hopitalId', primary_key=True, serialize=False)),
                ('nomhopital', models.CharField(db_column='nomHopital', max_length=100)),
                ('localisation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hopital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('medicamentid', models.AutoField(db_column='medicamentId', primary_key=True, serialize=False)),
                ('nommedicament', models.CharField(db_column='nomMedicament', max_length=100)),
            ],
            options={
                'db_table': 'medicament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordononce',
            fields=[
                ('ordononceid', models.AutoField(db_column='ordononceId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ordononce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soinobservation',
            fields=[
                ('compteur', models.AutoField(primary_key=True, serialize=False)),
                ('consultationdate', models.DateField(blank=True, db_column='consultationDate', null=True)),
                ('descriptionsoin', models.CharField(blank=True, db_column='descriptionSoin', max_length=200, null=True)),
                ('observation', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'soinobservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('nomuser', models.CharField(db_column='nomUser', max_length=100)),
                ('prenomuser', models.CharField(db_column='prenomUser', max_length=100)),
                ('emailuser', models.CharField(db_column='emailUser', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'tuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('patientid', models.OneToOneField(db_column='patientId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bdd.patient')),
                ('consultationdate', models.DateField(db_column='consultationDate')),
            ],
            options={
                'db_table': 'consultation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('patientid', models.OneToOneField(db_column='patientId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bdd.patient')),
                ('qr', models.CharField(db_column='QR', max_length=100)),
            ],
            options={
                'db_table': 'dpi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordononcemedicament',
            fields=[
                ('ordononceid', models.OneToOneField(db_column='ordononceId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bdd.ordononce')),
                ('dose', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ordononcemedicament',
                'managed': False,
            },
        ),
    ]
