# Generated by Django 5.1.4 on 2024-12-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilanbiologique',
            fields=[
                ('bilanbiologiqueid', models.AutoField(db_column='bilanBiologiqueId', primary_key=True, serialize=False)),
                ('typebilan', models.CharField(db_column='typeBilan', max_length=12)),
                ('graphimage', models.TextField(blank=True, db_column='graphImage', null=True)),
            ],
            options={
                'db_table': 'bilanbiologique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bilanradiologique',
            fields=[
                ('bilanradiologiqueid', models.AutoField(db_column='bilanRadiologiqueId', primary_key=True, serialize=False)),
                ('radiotype', models.CharField(db_column='RadioType', max_length=12)),
                ('compterendu', models.CharField(db_column='compteRendu', max_length=500)),
            ],
            options={
                'db_table': 'bilanradiologique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bilanradiologiqueimages',
            fields=[
                ('imageid', models.AutoField(db_column='imageId', primary_key=True, serialize=False)),
                ('imagedata', models.TextField(db_column='imageData')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bilanradiologiqueimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demandebilan',
            fields=[
                ('demandebilanid', models.AutoField(db_column='demandeBilanId', primary_key=True, serialize=False)),
                ('etatdemande', models.IntegerField(db_column='etatDemande')),
                ('typebilan', models.CharField(db_column='typeBilan', max_length=12)),
            ],
            options={
                'db_table': 'demandebilan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demandecertaficat',
            fields=[
                ('demandecertaficatid', models.AutoField(db_column='demandeCertaficatId', primary_key=True, serialize=False)),
                ('etatdemande', models.IntegerField(db_column='etatDemande')),
                ('contenudemande', models.CharField(db_column='contenuDemande', max_length=100)),
                ('datedenvoi', models.DateField(blank=True, db_column='dateDenvoi', null=True)),
            ],
            options={
                'db_table': 'demandecertaficat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demanderadio',
            fields=[
                ('demanderadioid', models.AutoField(db_column='demandeRadioId', primary_key=True, serialize=False)),
                ('etatdemande', models.IntegerField(db_column='etatDemande')),
                ('typeradio', models.CharField(db_column='typeRadio', max_length=12)),
            ],
            options={
                'db_table': 'demanderadio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('ordonnanceid', models.AutoField(db_column='ordonnanceId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ordonnance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordonnancemedicament',
            fields=[
                ('ordonnanceid', models.OneToOneField(db_column='ordonnanceId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bdd.ordonnance')),
                ('dose', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ordonnancemedicament',
                'managed': False,
            },
        ),
    ]
