# Generated by Django 5.1.4 on 2024-12-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0004_alter_consultation_options_and_more'),
    ]

    operations = [
       
    ]
